micarray: dynamicarray.o 
	g++ -Wall dynamicarray.o test_objects/student.o test_objects/profile.o -o dynamicarray -L../../lib/ -lds -lboost_unit_test_framework

dynamicarray.o: dynamicarray.cpp
	g++ -Wall -c dynamicarray.cpp 	
